dist: xenial
sudo: false
language: python
cache: pip
install: pip install 'tox-travis>=0.12,<1'
script: tox
stages:
- test
- deploy
jobs:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - stage: deploy
    python: 3.9
    install: pip install -e .[testing]
    script: skip
    before_deploy: tox -e package
    deploy:
      provider: pypi
      skip_cleanup: true
      distributions: bdist_wheel
      on:
        tags: true
      username: tiborhari
      password:
        secure: qaOQJzICUgPTSL7CRu3W/EfeRIkLYy+bEB/T1B9OUc2M8405zTO4qehE6RzuLnXpYJK51LtNH9R9vCSkPiVdtFBQv6gsbMq61BOrw8pwOxplO75GU5C6tZFF/l2x2WABQvWoJfqRApCrZSBrlb1McvIjANyYOo8/B/YWMDONQ93o0/jrdAiR9G1yxwwF1PV1naeKux52zt7DK0GUxSyHPIkZP7B82Sqnf3z+Zxxy2c2IlsJcQ6wcjVYp5WXB/veWg9TZxOx2cYqqnFOWe5TkhYCiLuwa1ZLtUx6efWNUorA/uexIttkcE1BlkQVFJFwaF4qDwNasHflprM3B13H1p+fN075gEumMt9HhaxIQwjmR8AxC7h8R1U7ciI78HOLIvFsm+DANXuN5Wa756M15oi2cVVwEnFruGu61NYDN329hnapV+SAwOCNFpHGAMh+yKkTkgqXvd8cJetf1fw+AWp5KDNntl4DTxrdpBm4lKlNKmraXRQN4T6Eu71Be7/t5uMJuccer+11x/QzUTlEhNNpWXLjiqtErYHrMkulI2fMIMXmVOXuXi/c5QwTDHeyuOV5YAzEkXG+81a+iGlhJWzqZ4yA4kWw2B6yg9Fi9evNIxc41HNG9Dm0wo2qCxFAiPpmkZRskwd3iaauVUqNMmpyoMcYuxU4eI+NWkTeQ9JY=
